# Node.js with React
# Step 1: Pull the code
# Step 2: Install the dependencies & build
# Step 3: Collect artifacts
# Step 4: Deploy to server

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn run build
  displayName: 'Run yarn install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/build
    artifactName: build

- script: |
    tar czvf build.tar.gz build
  displayName: 'Tarball the artifact'

- task: InstallSSHKey@0
  inputs:
    sshKeySecureFile: 'id_rsa.azure'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 20.222.12.161
    overwrite: true
    sourceFolder: 'build'
    targetFolder: '/home/xjtluoj/artifacts'

- task: SSH@0
  inputs:
    sshEndpoint: 20.222.12.161
    runOptions: 'script'
    scriptPath: '/home/xjtluoj/deploy.sh'
    failOnStdErr: true