# Node.js with React
# Step 1: Pull the code
# Step 2: Install the dependencies & build
# Step 3: Collect artifacts
# Step 4: Deploy to server

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17'
  displayName: 'Install Node.js'

- displayName: 'Run yarn install and build'
  script: |
    yarn install
    yarn run build

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/build
    artifactName: build
