# Node.js with React
# Step 1: Pull the code
# Step 2: Install the dependencies & build
# Step 3: Collect artifacts
# Step 4: Deploy to server

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17'
  displayName: 'Install Node.js'

- bash: |
    git push --prune https://$(GITHUB_PAT)@github.com/$(REPO_PATH).git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Mirror to GitHub'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    yarn config set network-timeout 300000
    yarn install
    yarn run build-prod
  displayName: 'Run yarn install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/build
    artifactName: build

- script: |
    tar czvf build.tar.gz build
  displayName: 'Tarball the artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/build.tar.gz
    artifactName: build_tarball

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: TARGET_SERVER
    overwrite: true
    sourceFolder: 'build'
    targetFolder: '/home/xjtluoj/.ci_build_frontend/artifacts'

- task: SSH@0
  inputs:
    sshEndpoint: TARGET_SERVER
    runOptions: 'commands'
    commands: '/home/xjtluoj/.ci_build_frontend/deploy.sh'
    failOnStdErr: true
